export const TASKS_REFRESH_LIST = 'TASKS_REFRESH_LIST';
export const TASKS_LIST_REFRESHED = 'TASKS_LIST_REFRESHED';
export const TASKS_SET_FILTER = 'TASKS_SET_FILTER';

export const GENERAL_SHOW_ERROR = 'GENERAL_SHOW_ERROR';
export const GENERAL_HIDE_ERROR = 'GENERAL_HIDE_ERROR';

export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
